stages:
  - build
  - dockerize

yarn-build:
  image: node:14
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - build

docker:
  image: docker:dind
  stage: dockerize
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  needs:
    - job: yarn-build
      artifacts: true
